// src/lib/exporters.js
// Export questionnaire answers in multiple formats

/**
 * Export as plain text — preserves original question order,
 * inserts answers directly below each question
 */
export function exportTXT(qaResults, questionnaireName) {
  const lines = [
    "═══════════════════════════════════════════════════════════════",
    `  ${questionnaireName}`,
    `  Completed by VaultIQ AI Assistant`,
    `  Generated: ${new Date().toLocaleString()}`,
    "═══════════════════════════════════════════════════════════════\n",
  ];

  for (const qa of qaResults) {
    lines.push(`Q${qa.question_num || qa.num}. ${qa.question_text || qa.text}`);
    lines.push(`\nAnswer:\n${qa.answer_text || qa.answer}`);

    const cites = qa.citations || [];
    if (cites.length) lines.push(`\nSources: ${cites.join("; ")}`);

    if (qa.evidence) lines.push(`Evidence: "${qa.evidence}"`);

    const conf = Math.round((qa.confidence || 0) * 100);
    lines.push(`Confidence: ${conf}%`);
    if (qa.hallucination_risk === "high") lines.push("⚠ Flagged for manual review");

    lines.push("\n───────────────────────────────────────────────────────────\n");
  }

  download(lines.join("\n"), `${slug(questionnaireName)}_answers.txt`, "text/plain");
}

/**
 * Export as CSV — tabular format for filtering/tracking
 */
export function exportCSV(qaResults, questionnaireName) {
  const headers = ["Question #", "Question", "Answer", "Citations", "Confidence %", "Evidence", "Flagged"];
  const rows = qaResults.map(qa => [
    qa.question_num || qa.num,
    csvCell(qa.question_text || qa.text),
    csvCell(qa.answer_text || qa.answer),
    csvCell((qa.citations || []).join("; ")),
    Math.round((qa.confidence || 0) * 100),
    csvCell(qa.evidence || ""),
    qa.hallucination_risk === "high" ? "Yes" : "No",
  ]);

  const csv = [headers, ...rows].map(r => r.join(",")).join("\n");
  download(csv, `${slug(questionnaireName)}_answers.csv`, "text/csv");
}

/**
 * Export as DOCX using docx.js (loaded from CDN)
 * Preserves original question structure with answers below each question
 */
export async function exportDOCX(qaResults, questionnaireName) {
  // docx.js — add to index.html:
  // <script src="https://unpkg.com/docx@8.5.0/build/index.js"></script>
  const docx = window.docx;
  if (!docx) {
    alert("DOCX export requires docx.js CDN. Falling back to TXT.");
    return exportTXT(qaResults, questionnaireName);
  }

  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = docx;

  const children = [
    new Paragraph({
      text: questionnaireName,
      heading: HeadingLevel.TITLE,
    }),
    new Paragraph({
      children: [new TextRun({ text: `Generated by VaultIQ AI · ${new Date().toLocaleString()}`, color: "888888", size: 20 })],
      spacing: { after: 400 },
    }),
  ];

  for (const qa of qaResults) {
    const num = qa.question_num || qa.num;
    const question = qa.question_text || qa.text;
    const answer = qa.answer_text || qa.answer;
    const conf = Math.round((qa.confidence || 0) * 100);
    const cites = (qa.citations || []).join("; ") || "—";
    const flagged = qa.hallucination_risk === "high";

    // Question
    children.push(new Paragraph({
      children: [new TextRun({ text: `Q${num}. ${question}`, bold: true, size: 24 })],
      spacing: { before: 300, after: 100 },
    }));

    // Answer
    children.push(new Paragraph({
      children: [new TextRun({ text: answer, size: 22 })],
      spacing: { after: 80 },
      indent: { left: 360 },
    }));

    // Citations
    children.push(new Paragraph({
      children: [
        new TextRun({ text: "Sources: ", bold: true, size: 20, color: "5b4fd1" }),
        new TextRun({ text: cites, size: 20, color: "5b4fd1" }),
      ],
      indent: { left: 360 },
    }));

    // Evidence
    if (qa.evidence) {
      children.push(new Paragraph({
        children: [new TextRun({ text: `"${qa.evidence}"`, italics: true, size: 18, color: "666666" })],
        indent: { left: 360 },
        spacing: { after: 60 },
      }));
    }

    // Confidence + flag
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `Confidence: ${conf}%`, size: 18, color: conf >= 75 ? "2d8a64" : conf >= 45 ? "c47a1a" : "cc3333" }),
        ...(flagged ? [new TextRun({ text: "  ⚠ Flagged for manual review", size: 18, color: "cc3333" })] : []),
      ],
      indent: { left: 360 },
      spacing: { after: 200 },
    }));
  }

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  download(blob, `${slug(questionnaireName)}_answers.docx`, "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
}

/**
 * Export as PDF using browser print-to-PDF flow.
 * Includes question, answer, citations, and evidence in a clean printable layout.
 */
export function exportPDF(qaResults, questionnaireName) {
  const win = window.open("", "_blank");
  if (!win) {
    alert("Popup blocked. Please allow popups to export PDF.");
    return;
  }

  const cards = qaResults.map((qa) => {
    const num = qa.question_num || qa.num;
    const question = escapeHtml(qa.question_text || qa.text || "");
    const answerRaw = qa.answer_text || qa.answer || "";
    const isNotFound = answerRaw.includes("Not found");
    const answer = isNotFound
      ? "Not found in references."
      : escapeHtml(answerRaw);
    const citations = (qa.citations || []).map(c => `<span class="cite">[DOC] ${escapeHtml(c)}</span>`).join("");
    const evidence = qa.evidence ? `<div class="evidence"><div class="label">Evidence</div>"${escapeHtml(qa.evidence)}"</div>` : "";

    return `
      <section class="card">
        <h3>Q${num}. ${question}</h3>
        <div class="answer">${answer}</div>
        ${citations ? `<div class="cites">${citations}</div>` : ""}
        ${evidence}
      </section>
    `;
  }).join("");

  win.document.write(`
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(questionnaireName)} - VaultIQ Export</title>
        <style>
          body { font-family: Arial, sans-serif; color: #0f172a; margin: 28px; line-height: 1.5; }
          h1 { margin: 0 0 8px; font-size: 24px; }
          .meta { color: #64748b; font-size: 12px; margin-bottom: 18px; }
          .card { border: 1px solid #dbe4ef; border-radius: 10px; padding: 14px 16px; margin-bottom: 12px; }
          .card h3 { margin: 0 0 8px; font-size: 15px; }
          .answer { font-size: 13px; margin-bottom: 8px; }
          .cites { margin-bottom: 8px; }
          .cite { display: inline-block; font-size: 11px; background: #eff6ff; border: 1px solid #c7dcff; color: #1d4ed8; border-radius: 999px; padding: 3px 8px; margin-right: 4px; margin-bottom: 4px; }
          .evidence { border-left: 3px solid #2563eb; background: #f8fbff; padding: 8px 10px; font-size: 11px; font-family: "Courier New", monospace; color: #334155; }
          .label { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #1d4ed8; margin-bottom: 4px; font-family: Arial, sans-serif; }
          @media print { body { margin: 14mm; } }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(questionnaireName)}</h1>
        <div class="meta">Generated by VaultIQ • ${escapeHtml(new Date().toLocaleString())}</div>
        ${cards}
      </body>
    </html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

// ── Helpers ───────────────────────────────────────────────

function csvCell(val) {
  const s = String(val || "").replace(/"/g, '""');
  return `"${s}"`;
}

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").slice(0, 40);
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function download(content, filename, mimeType) {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
